###
# Special targets to be done at end of all target
###
all-special: bin/perf-test-concurrent bin/unit-test-concurrent \
             bin/unit-test-concurrent-containers \
             bin/perf-test-containers bin/unit-test-containers

# Concurrent Performance Test
bin/perf-test-concurrent: $(OBJECTS_ROOT_DIR)/concurrent/PerfTestConcurrent.o $(TARGET_LIBRARY)
	$(CXX) $(CXX_FLAGS) $(OBJECTS_ROOT_DIR)/concurrent/PerfTestConcurrent.o $(LINKER_FLAGS) -o $@

# Concurrent Unit Test
bin/unit-test-concurrent: $(OBJECTS_ROOT_DIR)/concurrent/UnitTestConcurrent.o $(TARGET_LIBRARY)
	$(CXX) $(CXX_FLAGS) $(OBJECTS_ROOT_DIR)/concurrent/UnitTestConcurrent.o $(LINKER_FLAGS) -o $@

# Concurrent Containers Unit Test
bin/unit-test-concurrent-containers: $(OBJECTS_ROOT_DIR)/concurrent/containers/UnitTest.o $(TARGET_LIBRARY)
	$(CXX) $(CXX_FLAGS) $(OBJECTS_ROOT_DIR)/concurrent/containers/UnitTest.o $(LINKER_FLAGS) -o $@

# Container Performance Test
bin/perf-test-containers: $(OBJECTS_ROOT_DIR)/containers/PerfTestContainers.o $(TARGET_LIBRARY)
	$(CXX) $(CXX_FLAGS) $(OBJECTS_ROOT_DIR)/containers/PerfTestContainers.o $(LINKER_FLAGS) -o $@

# Container Unit Test
bin/unit-test-containers: $(OBJECTS_ROOT_DIR)/containers/UnitTestContainers.o $(TARGET_LIBRARY)
	$(CXX) $(CXX_FLAGS) $(OBJECTS_ROOT_DIR)/containers/UnitTestContainers.o $(LINKER_FLAGS) -o $@

####
# Special targets to be done at end of clean target
####
clean-special:

